###############################################################################
#                               Playground Env                               #
###############################################################################
version: "3.1"
services:
  dev:
    build: ./
    working_dir: /application
    volumes:
    - .:/application
